include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - public_member_api_docs
  disabledRules:
    # prefer_initializing_formals is too strict with private fields,
    # which cannot be exposed as public initializing formals
    - prefer_initializing_formals
