name: layrz_ui
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/goldenm-software/layrz_ui
repository: https://github.com/goldenm-software/layrz_ui

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
