import 'package:flutter/widgets.dart';

import 'ai_marker.dart';
import 'ai_marker_position.dart';

/// Overlays a [LayrzAiMarker] on a corner of [child] without affecting
/// [child]'s layout footprint.
///
/// Follows `LayrzBadge`'s pattern (`lib/src/badges/src/badge.dart`): a
/// [Stack] + [Positioned] + [FractionalTranslation] overlay, painted on top
/// of [child] so wrapping any widget with a marker never reflows the
/// surrounding layout. This does **not** reuse `LayrzBadgeVisual` — that
/// visual is a single-glyph, count-shaped surface with count-oriented
/// semantics, which has no room for [LayrzAiMarker]'s two overlapping,
/// differently-sized, continuously-animating sparkle glyphs.
///
/// Unlike [LayrzBadge], [child]'s semantics are **not** excluded or merged
/// with the marker's: a badge count is meaningless without the icon it
/// decorates ("3 unread" only makes sense attached to a bell), but AI
/// disclosure and [child]'s own content are two independent facts a screen
/// reader user needs separately — "this is a chat bubble reading X" AND
/// "this content was generated by AI" are both worth hearing on their own.
/// [LayrzAiMarker] attaches its own mandatory disclosure [Semantics] node
/// (sourced from `LayrzUiL10n.aiGeneratedLabel`) as a sibling in the tree, so
/// both announcements survive independently.
///
/// Like [LayrzAiMarker], the overlaid marker's disclosure label and tooltip
/// are **not** configurable here either — there is no
/// `semanticsLabel`/`tooltip` parameter. Both always come from
/// `LayrzUiL10n.of(context)` for the same reason: the disclosure text is
/// legally load-bearing and must be identical, and identically translated,
/// at every call site.
@immutable
class LayrzAiMarkerWrapper extends StatelessWidget {
  /// Creates an overlay wrapping [child] with a [LayrzAiMarker] at
  /// [position].
  const LayrzAiMarkerWrapper({
    super.key,
    required this.child,
    this.position = LayrzAiMarkerPosition.topRight,
    this.size = 24.0,
    this.isVisible = true,
  });

  /// The widget the AI-disclosure marker is overlaid on.
  ///
  /// The marker is painted on top of [child] via a [Positioned] overlay and
  /// never affects [child]'s layout size.
  final Widget child;

  /// Which corner of [child] the marker is anchored to.
  ///
  /// Defaults to [LayrzAiMarkerPosition.topRight].
  final LayrzAiMarkerPosition position;

  /// The overall footprint of the overlaid marker, in logical pixels. See
  /// [LayrzAiMarker.size].
  final double size;

  /// Whether the marker is shown at all.
  ///
  /// When `false`, only [child] is rendered — no marker visual, no corner
  /// overlay, and no disclosure semantics are painted or attached. Use this
  /// to toggle disclosure based on whether the decorated content is actually
  /// AI-generated, while keeping the widget tree stable. Defaults to `true`.
  final bool isVisible;

  @override
  Widget build(BuildContext context) {
    if (!isVisible) return child;

    return Stack(
      clipBehavior: Clip.none,
      children: [
        child,
        Positioned.fill(
          child: Align(
            alignment: position.alignment,
            child: FractionalTranslation(
              translation: position.translation,
              child: LayrzAiMarker(size: size),
            ),
          ),
        ),
      ],
    );
  }
}
