/// AI-disclosure namespace.
///
/// Carries the mandatory AI-generated-content disclosure text used by
/// `LayrzAiMarker` (`lib/src/ai_marker/src/ai_marker.dart`). This text is
/// legally load-bearing — it is the mechanism by which the design system
/// discloses AI-generated or AI-assisted content to screen reader users
/// ([aiGeneratedLabel]) and to sighted users who hover or long-press the
/// marker ([aiGeneratedTooltip]). Deliberately **not** configurable from the
/// call site: the disclosure text must be a single, consistent, translated
/// string across every use of [LayrzAiMarker] in the design system, never a
/// per-caller override.
mixin LayrzUiL10nAiMixin {
  /// Localized [Semantics] label announced for an AI-disclosure marker.
  ///
  /// Default: "Generated by AI".
  String get aiGeneratedLabel => 'Generated by AI';

  /// Localized tooltip text shown when an AI-disclosure marker is hovered or
  /// long-pressed.
  ///
  /// Default: "Generated by AI".
  String get aiGeneratedTooltip => 'Generated by AI';
}
