import 'package:flutter/foundation.dart';
import 'package:flutter/painting.dart';

/// A colour with a range of tonal shades, equivalent to Material's `MaterialColor`
/// but built on [ColorSwatch] so it carries no Material dependency.
///
/// [LayrzColorSwatch] extends [ColorSwatch<int>] and provides ten shade getters
/// (50, 100, 200, …, 900) for accessing tonal variants of the primary color.
/// The primary color is stored at index 500 and accessible via [shade500].
///
/// This class can be constructed directly with a primary color and a map of shades,
/// or via the [LayrzColorSwatch.fromColor] factory to generate shades algorithmically.
@immutable
class LayrzColorSwatch extends ColorSwatch<int> {
  /// Creates a color swatch with a primary color and a map of tonal shades.
  ///
  /// [primary] is the primary color value, typically matching the 500 shade.
  /// [swatch] is a map of shade indices (50, 100, …, 900) to their [Color] values.
  const LayrzColorSwatch(super.primary, super.swatch);

  /// The lightest shade (50).
  Color get shade50 => this[50]!;

  /// The second lightest shade (100).
  Color get shade100 => this[100]!;

  /// The third lightest shade (200).
  Color get shade200 => this[200]!;

  /// The fourth lightest shade (300).
  Color get shade300 => this[300]!;

  /// The fifth lightest shade (400).
  Color get shade400 => this[400]!;

  /// The default/primary shade (500).
  Color get shade500 => this[500]!;

  /// The fourth darkest shade (600).
  Color get shade600 => this[600]!;

  /// The third darkest shade (700).
  Color get shade700 => this[700]!;

  /// The second darkest shade (800).
  Color get shade800 => this[800]!;

  /// The darkest shade (900).
  Color get shade900 => this[900]!;

  @override
  int get hashCode => toARGB32();

  @override
  bool operator ==(Object other) => identical(this, other) || other is Color && other.toARGB32() == toARGB32();

  /// Generates a full shade range from a single seed colour.
  ///
  /// This factory derives all ten shades by varying the lightness of the seed colour
  /// in HSL (Hue, Saturation, Lightness) space. The seed colour is always pinned to
  /// the 500 shade (the default), and lighter shades (50–400) are generated by increasing
  /// lightness, while darker shades (600–900) are generated by decreasing lightness.
  ///
  /// The progression is deterministic: each step adjusts lightness by a fixed
  /// increment around the seed's natural lightness, ensuring that [shade500]
  /// is always exactly equal to the [seed].
  factory LayrzColorSwatch.fromColor(Color seed) {
    final hslColor = HSLColor.fromColor(seed);
    final baseLightness = hslColor.lightness;

    // Generate shades by varying lightness symmetrically around the seed's lightness.
    // Each step adjusts lightness by approximately ±10% or less.
    const lightnessDifferences = [-0.40, -0.35, -0.25, -0.15, -0.05, 0.0, 0.10, 0.20, 0.30, 0.40];
    const shadeIndices = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900];

    final swatch = <int, Color>{};
    for (int i = 0; i < lightnessDifferences.length; i++) {
      final targetLightness = (baseLightness + lightnessDifferences[i]).clamp(0.0, 1.0);
      final adjustedHsl = hslColor.withLightness(targetLightness);
      swatch[shadeIndices[i]] = adjustedHsl.toColor();
    }

    return LayrzColorSwatch(seed.toARGB32(), swatch);
  }
}
