import 'package:flutter/widgets.dart';
import 'package:flutter_material_design_icons/flutter_material_design_icons.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:layrz_ui/layrz_ui.dart';

import '../helpers/pump_themed.dart';

void main() {
  group('LayrzAiMarker', () {
    testWidgets('renders two star glyphs', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker());

      expect(find.byWidgetPredicate((w) => w is Icon && w.icon == MdiIcons.starFourPointsSmall), findsNWidgets(2));
    });

    testWidgets('renders no visible text label', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker());

      // Icon-only, by hard requirement: there is no label parameter to opt
      // into, so no Text widget should ever appear -- Icon itself renders
      // via an internal RichText carrying a single glyph codepoint (not a
      // human-readable string), so that is not what this test guards
      // against; a real accidental label would show up as a Text widget.
      expect(find.byType(Text), findsNothing);
    });

    testWidgets('star color resolves to tokens.colors.aiAccent', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final theme = LayrzThemeData.light();
      await pumpThemed(tester, const LayrzAiMarker(), theme: theme);

      final icons = tester.widgetList<Icon>(
        find.byWidgetPredicate((w) => w is Icon && w.icon == MdiIcons.starFourPointsSmall),
      );
      expect(icons, isNotEmpty);
      for (final icon in icons) {
        expect(icon.color, theme.tokens.colors.aiAccent);
      }
    });

    testWidgets('the marker footprint matches the size parameter', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      const size = 40.0;
      await pumpThemed(tester, const LayrzAiMarker(size: size));

      final box = tester.widget<SizedBox>(
        find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(SizedBox)).first,
      );
      expect(box.width, size);
      expect(box.height, size);
    });

    testWidgets('a tooltip is present wrapping the marker', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker());

      expect(find.byType(LayrzTooltip), findsOneWidget);
      final tooltip = tester.widget<LayrzTooltip>(find.byType(LayrzTooltip));
      expect(tooltip.contentText, 'Generated by AI');
    });

    testWidgets('the tooltip text is overridable', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker(tooltip: 'This summary was generated by AI'));

      final tooltip = tester.widget<LayrzTooltip>(find.byType(LayrzTooltip));
      expect(tooltip.contentText, 'This summary was generated by AI');
    });

    testWidgets('reduce motion: renders statically with no AnimatedBuilder driving frames', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await tester.pumpWidget(
        Localizations(
          locale: const Locale('en'),
          delegates: const [DefaultWidgetsLocalizations.delegate, LayrzUiL10nDelegate()],
          child: LayrzTheme(
            data: LayrzThemeData.light(),
            child: Overlay(
              initialEntries: [
                OverlayEntry(
                  builder: (context) => MediaQuery(
                    data: MediaQuery.of(context).copyWith(disableAnimations: true),
                    child: const Center(child: LayrzAiMarker()),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
      await tester.pump();

      // No AnimatedBuilder should be present anywhere under the marker when
      // motion is disabled -- both the burst and the shine glint are torn
      // down entirely, not merely paused.
      expect(find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(AnimatedBuilder)), findsNothing);
      expect(find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(ShaderMask)), findsNothing);

      // Pumping several frames must not throw and must not change anything
      // -- there is no ticking controller left to advance.
      await tester.pump(const Duration(milliseconds: 500));
      expect(find.byWidgetPredicate((w) => w is Icon && w.icon == MdiIcons.starFourPointsSmall), findsNWidgets(2));
    });

    testWidgets('motion enabled: an AnimatedBuilder drives the burst and the glint', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker());

      expect(find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(AnimatedBuilder)), findsWidgets);
      expect(find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(ShaderMask)), findsOneWidget);
    });

    testWidgets('the two stars are not rendered at identical scale mid-cycle (staggered burst is live)', (
      tester,
    ) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(tester, const LayrzAiMarker());
      // Advance partway into the loop -- enough for the big star to be
      // mid-bounce while the small star's delayed interval has only just
      // begun (or not yet), matching the burst helper's own staggered-phase
      // unit test.
      await tester.pump(const Duration(milliseconds: 400));

      final scaleTransforms = tester
          .widgetList<Transform>(
            find.descendant(of: find.byType(LayrzAiMarker), matching: find.byType(Transform)),
          )
          .toList();

      expect(scaleTransforms.length, 2);
      final scaleA = scaleTransforms[0].transform.getMaxScaleOnAxis();
      final scaleB = scaleTransforms[1].transform.getMaxScaleOnAxis();
      expect(scaleA, isNot(closeTo(scaleB, 0.001)));
    });
  });

  group('LayrzAiMarker accessibility', () {
    testWidgets('the mandatory semantics disclosure label is present and announced', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(tester, const LayrzAiMarker());

        expect(
          tester.getSemantics(find.byType(LayrzAiMarker)),
          matchesSemantics(label: 'Generated by AI', isImage: true),
        );
      } finally {
        handle.dispose();
      }
    });

    testWidgets('the semantics label is overridable', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(tester, const LayrzAiMarker(semanticsLabel: 'This summary was generated by AI'));

        expect(
          tester.getSemantics(find.byType(LayrzAiMarker)),
          matchesSemantics(label: 'This summary was generated by AI', isImage: true),
        );
      } finally {
        handle.dispose();
      }
    });

    testWidgets('the star glyphs do not surface a separate semantics node', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(tester, const LayrzAiMarker());

        // The marker's own Semantics node carries the label; the inner Icons
        // must be excluded so no unlabelled/duplicate node appears alongside
        // it (mirrors LayrzBadge's ExcludeSemantics-over-child pattern).
        final node = tester.getSemantics(find.byType(LayrzAiMarker));
        expect(node.label, 'Generated by AI');
      } finally {
        handle.dispose();
      }
    });

    testWidgets('exposes a tooltip semantics hint', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(tester, const LayrzAiMarker());

        // LayrzTooltip attaches a `tooltip:` semantics hint on its own
        // Semantics node (see tooltip.dart's build()), which wraps
        // LayrzAiMarker's own content -- so it is a descendant of the
        // LayrzAiMarker element, not an ancestor. Assert it carries the same
        // disclosure text as a redundant availability path.
        final tooltipSemantics = find.descendant(
          of: find.byType(LayrzAiMarker),
          matching: find.byWidgetPredicate((w) => w is Semantics && w.properties.tooltip == 'Generated by AI'),
        );
        expect(tooltipSemantics, findsWidgets);
      } finally {
        handle.dispose();
      }
    });
  });
}
