import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:layrz_ui/layrz_ui.dart';

import '../helpers/pump_themed.dart';

void main() {
  group('LayrzAiMarkerWrapper', () {
    testWidgets('renders its child', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      const childKey = Key('wrapped-child');
      await pumpThemed(
        tester,
        LayrzAiMarkerWrapper(child: SizedBox(key: childKey, width: 100, height: 60)),
      );

      expect(find.byKey(childKey), findsOneWidget);
    });

    testWidgets('overlays a LayrzAiMarker on top of the child', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        const LayrzAiMarkerWrapper(child: SizedBox(width: 100, height: 60)),
      );

      expect(find.byType(LayrzAiMarker), findsOneWidget);
    });

    testWidgets('wrapping a child does not change its layout size', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      const bareKey = Key('bare-box');
      const wrappedKey = Key('wrapped-box');

      await pumpThemed(
        tester,
        Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(key: bareKey, width: 120, height: 80),
            LayrzAiMarkerWrapper(
              child: const SizedBox(key: wrappedKey, width: 120, height: 80),
            ),
          ],
        ),
      );

      final bareSize = tester.getSize(find.byKey(bareKey));
      final wrappedSize = tester.getSize(find.byKey(wrappedKey));
      expect(wrappedSize, equals(bareSize));
    });

    testWidgets('isVisible false renders only the child, no marker', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        const LayrzAiMarkerWrapper(isVisible: false, child: SizedBox(width: 100, height: 60)),
      );

      expect(find.byType(LayrzAiMarker), findsNothing);
    });

    for (final position in LayrzAiMarkerPosition.values) {
      testWidgets('positions the marker at $position without throwing', (tester) async {
        tester.view.physicalSize = const Size(800, 600);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.reset);

        await pumpThemed(
          tester,
          LayrzAiMarkerWrapper(position: position, child: const SizedBox(width: 100, height: 60)),
        );

        expect(find.byType(LayrzAiMarker), findsOneWidget);
      });
    }

    testWidgets('has no semanticsLabel/tooltip parameters -- the overlaid marker sources them from LayrzUiL10n', (
      tester,
    ) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        const LayrzAiMarkerWrapper(child: SizedBox(width: 100, height: 60)),
      );

      // LayrzAiMarkerWrapper has no semanticsLabel/tooltip parameters to
      // forward -- disclosure text is legally load-bearing and always comes
      // from LayrzUiL10n.of(context), not a per-caller override.
      final tooltip = tester.widget<LayrzTooltip>(find.byType(LayrzTooltip));
      expect(tooltip.contentText, 'Generated by AI');
    });

    testWidgets("the marker's size is forwarded", (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        const LayrzAiMarkerWrapper(size: 32, child: SizedBox(width: 100, height: 60)),
      );

      final marker = tester.widget<LayrzAiMarker>(find.byType(LayrzAiMarker));
      expect(marker.size, 32);
    });
  });

  group('LayrzAiMarker.wrap', () {
    testWidgets('produces a LayrzAiMarkerWrapper', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        LayrzAiMarker.wrap(child: const SizedBox(width: 100, height: 60)),
      );

      expect(find.byType(LayrzAiMarkerWrapper), findsOneWidget);
      expect(find.byType(LayrzAiMarker), findsOneWidget);
    });

    testWidgets('forwards child, position, size and isVisible identically to constructing '
        'LayrzAiMarkerWrapper directly', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      const childKey = Key('wrapped-child');

      await pumpThemed(
        tester,
        LayrzAiMarker.wrap(
          position: LayrzAiMarkerPosition.bottomLeft,
          size: 32,
          child: const SizedBox(key: childKey, width: 100, height: 60),
        ),
      );

      final wrapper = tester.widget<LayrzAiMarkerWrapper>(find.byType(LayrzAiMarkerWrapper));
      expect(wrapper.position, LayrzAiMarkerPosition.bottomLeft);
      expect(wrapper.size, 32);
      expect(wrapper.isVisible, isTrue);
      expect(find.byKey(childKey), findsOneWidget);

      final marker = tester.widget<LayrzAiMarker>(find.byType(LayrzAiMarker));
      expect(marker.size, 32);
    });

    testWidgets('isVisible false renders only the child, no marker', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      await pumpThemed(
        tester,
        LayrzAiMarker.wrap(isVisible: false, child: const SizedBox(width: 100, height: 60)),
      );

      expect(find.byType(LayrzAiMarker), findsNothing);
    });
  });

  group('LayrzAiMarkerWrapper accessibility', () {
    testWidgets('child content and the disclosure label both remain independently announced', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(
          tester,
          LayrzAiMarkerWrapper(
            child: Semantics(label: 'Chat message content', child: const SizedBox(width: 100, height: 60)),
          ),
        );

        // Unlike LayrzBadge (which excludes the child's semantics because the
        // count is meaningless without it), the wrapped child's own content
        // must remain independently announced here -- disclosure and content
        // are two separate facts.
        expect(find.bySemanticsLabel('Chat message content'), findsOneWidget);
        expect(find.bySemanticsLabel('Generated by AI'), findsOneWidget);
      } finally {
        handle.dispose();
      }
    });

    testWidgets('isVisible false attaches no disclosure semantics', (tester) async {
      tester.view.physicalSize = const Size(800, 600);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.reset);

      final handle = tester.ensureSemantics();
      try {
        await pumpThemed(
          tester,
          LayrzAiMarkerWrapper(
            isVisible: false,
            child: Semantics(label: 'Chat message content', child: const SizedBox(width: 100, height: 60)),
          ),
        );

        expect(find.bySemanticsLabel('Chat message content'), findsOneWidget);
        expect(find.bySemanticsLabel('Generated by AI'), findsNothing);
      } finally {
        handle.dispose();
      }
    });
  });
}
